apiVersion: deploy.ibm.com/v1
kind: DeploymentPlan
metadata:
  name: package.tar
  description: package.tar
  annotations:
    creation_timestamp: 20230915.130645.553
    engine:
      version: 3.0.1
      build: manual
      date: Thu Sep 14 17:37:56 CEST 2023
    package:
      path: package.tar
      sha256: 4be511f363cffd1e28ab51ce98a681c4d2b9067169fce9d8d748aa195c8e40b5
activities:
- name: PACKAGE
  properties: []
  actions:
  - name: PACKAGE
    properties: []
    steps:
    - name: PACKAGE
      properties:
      - key: is_remote
        value: false
      artifacts: []
  tags:
  - always
- name: MQCommand
  properties: []
  actions:
  - name: MQCommand
    properties: []
    steps:
    - name: MQCommand
      properties:
      - key: path_filter
        value: cmds_files/.*
      - key: template
        value: mq_command
      artifacts:
      - name: mq_cfstruct_yaml_cmds
        properties:
        - key: path
          value: cmds_files/mq_cfstruct_yaml_cmds.yml
        - key: type
          value: yml
        hash: dd1e151b4bd058496c6cc4757249c0d11e331fde13b3552785406f49ed869ead
  tags:
  - mq_command
manifests:
- name: package.tar
  description: package.tar
  annotations:
    creation_timestamp: 20230915.130645.553
